sudo: required 
services:
  - docker

before_install:
  - docker build -t adili/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adili/react-test npm test

after_success:
  - docker build -t adili/multi-client ./client
  - docker build -t adili/multi-nginx ./nginx
  - docker build -t adili/multi-server ./server
  - docker build -t adili/multi-worker ./worker
  #Login to docker CLI
  - echo "$Docker-PASSWORD" | docker login 0u "$Docker-ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push adili/multi-client
  - docker push adili/multi-nginx
  - docker push adili/multi-server
  - docker push adili/multi-worker
