sudo: required 
services:
  - docker

before_install:
  - docker build -t adi645/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adi645/react-test npm test

after_success:
  - docker build -t adi645/multi-client ./client
  - docker build -t adi645/multi-nginx ./nginx
  - docker build -t adi645/multi-server ./server
  - docker build -t adi645/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push adi645/multi-client
  - docker push adi645/multi-nginx
  - docker push adi645/multi-server
  - docker push adi645/multi-worker
