sudo: required 
services:
  - docker

before_install:
  - docker build -t adili/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adili/react-test npm test

after_success:
  - docker build -t adili/multi-client ./client
  - docker build -t adili/multi-nginx ./nginx
  - docker build -t adili/multi-server ./server
  - docker build -t adili/multi-worker ./worker